% Function to reduce the whitespace around the figure
% This function is generated by ChatGPT 4.0
function tighten_fig(hfig)
    % tightfig: tightens the margins of a figure window
    if nargin == 0
        hfig = gcf;
    end
    
    % Retrieve all axes in the figure
    hax = findall(hfig, 'type', 'axes');
    
    % Initialize the tightinset variable
    tightinset = [0, 0, 0, 0];
    
    % Loop through all axes and calculate the maximum tight inset
    for i = 1:length(hax)
        tightinset = max(tightinset, get(hax(i), 'TightInset'));
    end
    
    % Reduce the figure's outer position based on the tight inset
    set(hfig, 'OuterPosition', get(hfig, 'OuterPosition') - [tightinset(1:2), 0, 0]);
    
    % Adjust the position of each axis
    for i = 1:length(hax)
        pos = get(hax(i), 'Position');
        set(hax(i), 'Position', [pos(1) - 0.15/2, pos(2) + tightinset(1), pos(3) + 0.15, pos(4) - tightinset(4)]);
    end
end